[build]
  publish = "."
  
[build.environment]
  NODE_VERSION = "16"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[identity]
  external_providers = []

[services.git-gateway]
  enabled = true